# Generated by Django 4.1.2 on 2022-11-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='create',
            new_name='created',
        ),
    ]
